In [2]:
import numpy as np
import pandas as pd
import pingouin as pg

In [3]:
df = pd.read_csv('./data/after.csv')
df.drop(df.columns[0], axis=1, inplace=True)
df

,時間戳記,1. 您的实验编号？,2. 我能够感受到机器人的正面评价，如「你真厉害」、「做得很好」,3. 我能够感受到机器人把好的结果归因到了,4. 我能够感受到机器人的负面评价，如「做得不对」、「完成得不好」,5. 我能够感受到机器人把不好的结果归因到了,6. 我能够感受到机器人给我的评价,7. 我认同NAO对我的正面评价，我认为自己确实表现得不错,8. 我认为，在刚刚的实验任务中，动作完成得好主要是依赖于,9. 我认为，动作完成得好主要是______的功劳,...,75. 机器人只能做人类指示它去做的事情,76. 机器人永远不会做任何运行程序以外的事情,77. 我希望在本次实验中表现出色,78. 我相信我可以掌握本次实验中机器人教授的基本动作,79. 我相信我将在本次实验中取得优异的成绩,80. 我相信我可以掌握本次实验中机器人教授的动作,81. 我有信心在本次实验中表现出色,82. 我相信我能理解本次实验中机器人教授的困难动作,83. 我相信我能理解本次实验中机器人教授的复杂动作,84. 我相信我将在本次实验中出色地完成动作
0,2022-07-23 19:08:40.435,17,5,3,5,3,正面评价和负面评价相当,5,3,4,...,7,7,5,5,5,5,5,3,3,6
1,2022-07-24 10:42:36.312,25,7,2,7,6,正面评价更多,4,5,5,...,6,7,7,5,5,4,4,5,5,3
2,2022-07-24 11:30:04.161,49,6,3,6,2,正面评价和负面评价相当,4,4,3,...,5,3,6,5,3,4,3,4,3,3
3,2022-07-24 13:41:12.631,9,7,5,6,4,正面评价更多,4,5,4,...,7,7,7,4,4,4,2,1,1,1
4,2022-07-24 14:22:01.431,1,6,6,5,6,正面评价更多,4,4,3,...,4,3,6,5,6,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2022-07-31 10:44:46.640,56,7,1,7,1,正面评价和负面评价相当,5,2,2,...,7,7,4,7,7,7,7,7,7,6
60,2022-07-31 11:30:54.182,24,5,5,6,3,正面评价和负面评价相当,5,3,3,...,5,4,6,5,5,5,5,5,6,5
61,2022-07-31 12:42:42.503,32,7,2,5,7,正面评价更多,4,5,4,...,7,2,6,6,5,6,6,6,6,5
62,2022-08-01 10:20:24.240,14,5,3,5,4,正面评价更多,6,2,3,...,5,5,6,6,6,6,6,6,6,6
63,2022-08-01 11:20:49.457,64,5,3,5,6,正面评价和负面评价相当,2,4,4,...,4,4,6,5,2,2,2,2,2,2

In [4]:
df.iloc[:, 33:36]

    33. 听到机器人的正面评价，我会认为自己受到了表扬  34. 我认为机器人有资格对我提出表扬  35. 我认可和接受机器人对我表扬
0                            5                    5                  4
1                            6                    5                  5
2                            5                    5                  5
3                            7                    7                  7
4                            6                    5                  6
..                         ...                  ...                ...
59                           1                    7                  1
60                           4                    5                  4
61                           6                    6                  7
62                           6                    6                  6
63                           3                    4                  4

[64 rows x 3 columns]

In [5]:
pg.cronbach_alpha(data=df.iloc[:, 33:36])

(np.float64(0.8188626525891487), array([0.726, 0.884]))

This is my first implementation of Cronbach's Alpha, a rather nice success. Other than this, I think I "only" need to learn how to do ANOVA Data Analysis properly.

In [6]:
df.iloc[:, 36:39]

    36. 听到机器人的负面评价，我会认为自己受到了批评  37. 我认为机器人有资格对我提出批评  38. 我认可和接受机器人对我的批评
0                            6                    4                   4
1                            7                    4                   4
2                            5                    5                   5
3                            4                    4                   5
4                            5                    4                   4
..                         ...                  ...                 ...
59                           1                    7                   1
60                           5                    5                   5
61                           3                    6                   5
62                           4                    5                   5
63                           3                    4                   4

[64 rows x 3 columns]

In [7]:
pg.cronbach_alpha(data=df.iloc[:, 36:39])

(np.float64(0.5618394609291877), array([0.336, 0.72 ]))

I am guessing the value would increase dramatically if the "ID" data points are removed

In [3]:
EI_dataset = pd.concat([df.iloc[0:8, 36:39], df.iloc[32:40, 36:39]])
ID_dataset = pd.concat([df.iloc[8:16, 36:39], df.iloc[40:48, 36:39]])
II_dataset = pd.concat([df.iloc[16:24, 36:39], df.iloc[48:56, 36:39]])
ED_dataset = pd.concat([df.iloc[24:32, 36:39], df.iloc[56:64, 36:39]])

test_df = pd.concat([II_dataset, EI_dataset, ED_dataset])
test_df.reset_index(drop=True, inplace=True)
test_df

    36. 听到机器人的负面评价，我会认为自己受到了批评  37. 我认为机器人有资格对我提出批评  38. 我认可和接受机器人对我的批评
0                            7                    7                   3
1                            4                    6                   6
2                            3                    3                   3
3                            6                    5                   5
4                            3                    5                   5
5                            1                    7                   7
6                            2                    4                   5
7                            5                    4                   4
8                            5                    5                   5
9                            7                    3                   3
10                           7                    6                   6
11                           5                    6                   5
12                           5                    4                   3
13                           4                    2                   3
14                           2                    5                   6
15                           3                    5                   5
16                           6                    4                   4
17                           7                    4                   4
18                           5                    5                   5
19                           4                    4                   5
20                           5                    4                   4
21                           3                    3                   3
22                           4                    6                   6
23                           5                    4                   3
24                           7                    7                   7
25                           5                    6                   4
26                           6                    6                   5
27                           2                    6                   3
28                           4                    3                   3
29                           3                    3                   3
30                           5                    6                   6
31                           5                    5                   5
32                           5                    5                   4
33                           7                    6                   6
34                           3                    5                   5
35                           6                    6                   6
36                           5                    5                   5
37                           3                    5                   4
38                           4                    6                   6
39                           5                    3                   3
40                           4                    6                   7
41                           7                    5                   2
42                           5                    6                   6
43                           1                    7                   1
44                           5                    5                   5
45                           3                    6                   5
46                           4                    5                   5
47                           3                    4                   4

In [7]:
pg.cronbach_alpha(data=EI_dataset)

(np.float64(0.7512038523274479), array([0.426, 0.906]))

In [8]:
pg.cronbach_alpha(data=ID_dataset)

(np.float64(0.8057570262919311), array([0.552, 0.927]))

In [9]:
pg.cronbach_alpha(data=II_dataset)

(np.float64(0.07010869565217376), array([-1.145,  0.648]))

In [10]:
pg.cronbach_alpha(data=ED_dataset)

(np.float64(0.3028603477285473), array([-0.608,  0.736]))

In [60]:
df.iloc[:, 39:44]

,39. 机器人的正面评价让我感到,40. 机器人的正面反馈让我感到,41. 机器人的正面反馈能够______我学习的热情,42. 机器人的正面反馈______了我的自信,43. 机器人的正面反馈______了我的学习动力
0,6,6,5,5,5
1,7,6,7,6,6
2,6,6,5,5,5
3,5,5,6,7,7
4,5,3,6,6,6
...,...,...,...,...,...
59,4,7,4,4,4
60,4,5,5,5,5
61,6,7,4,4,5
62,5,5,6,6,6
63,5,3,5,5,5

In [61]:
pg.cronbach_alpha(data=df.iloc[:, 39:44])

(np.float64(0.8313969837346634), array([0.756, 0.889]))

In [62]:
df.iloc[:, 45:50]

,45. 机器人的负面评价让我感到,46. 机器人的负面反馈让我感到,47. 机器人的负面反馈能够______我学习的热情,48. 机器人的负面反馈______了我的自信,49. 机器人的负面反馈______了我的学习动力
0,3,2,2,2,2
1,1,1,2,1,1
2,3,3,3,3,3
3,4,4,4,4,4
4,3,3,3,4,3
...,...,...,...,...,...
59,1,3,5,6,6
60,2,2,2,3,2
61,3,4,5,5,6
62,3,3,4,4,5
63,4,4,4,4,4

In [63]:
pg.cronbach_alpha(data=df.iloc[:, 45:50])

(np.float64(0.8473064343059561), array([0.779, 0.899]))

In [58]:
stats.shapiro(stats.boxcox(pd.concat([df.iloc[0:8, test_list[9]], df.iloc[32:40, test_list[9]]]).tolist())[0])[1]

np.float64(0.040063230165067035)

In [93]:
from sklearn.preprocessing import PowerTransformer
pt = PowerTransformer(method='yeo-johnson')

stats.shapiro(pt.fit_transform(np.array(pd.concat([df.iloc[0:8, test_list[7]], df.iloc[32:40, test_list[7]]]).tolist()).reshape(-1, 1)))[1]

array([[-0.01322185],
       [ 0.8718288 ],
       [-0.97377817],
       [-0.01322185],
       [-0.97377817],
       [-0.01322185],
       [ 0.8718288 ],
       [-0.97377817],
       [-2.03834994],
       [-0.01322185],
       [ 1.69865367],
       [-0.01322185],
       [-0.97377817],
       [-0.01322185],
       [ 1.69865367],
       [ 0.8718288 ]])

In [96]:
pt.fit_transform(np.array(pd.concat([df.iloc[8:16, test_list[7]], df.iloc[40:48, test_list[7]]]).tolist()).reshape(-1, 1)).tolist()

[[0.8654926430815412],
 [0.14984694483015448],
 [1.5336427493865437],
 [-0.6274322657504258],
 [0.8654926430815412],
 [-1.489689280862672],
 [0.14984694483015448],
 [0.8654926430815412],
 [0.14984694483015448],
 [-0.6274322657504258],
 [-0.6274322657504258],
 [1.5336427493865437],
 [-1.489689280862672],
 [-0.6274322657504258],
 [0.8654926430815412],
 [-1.489689280862672]]

In [113]:
pd.concat([df.iloc[8:16, 20], df.iloc[40:48, 20]]).tolist()

[4, 1, 7, 7, 6, 6, 7, 6, 7, 6, 6, 6, 7, 6, 7, 7]

In [107]:
import scipy.stats as stats
import numpy as np

test_list = list(range(0, 64))
test_list.remove(0)
test_list.remove(6)

for i in range(len(test_list)):
    EI_dataclip = stats.boxcox(pd.concat([df.iloc[0:8, test_list[i]], df.iloc[32:40, test_list[i]]]).tolist())[0]
    ID_dataclip = stats.boxcox(pd.concat([df.iloc[8:16, test_list[i]], df.iloc[40:48, test_list[i]]]).tolist())[0]
    II_dataclip = stats.boxcox(pd.concat([df.iloc[16:24, test_list[i]], df.iloc[48:56, test_list[i]]]).tolist())[0]
    ED_dataclip = stats.boxcox(pd.concat([df.iloc[24:32, test_list[i]], df.iloc[56:64, test_list[i]]]).tolist())[0]

    shapiro_test_EI = stats.shapiro(EI_dataclip)
    shapiro_test_ID = stats.shapiro(ID_dataclip)
    shapiro_test_II = stats.shapiro(II_dataclip)
    shapiro_test_ED= stats.shapiro(ED_dataclip)

    
    if shapiro_test_EI[1] > 0.05:
        shapiro_test_EI = 'Y'
    else:
        shapiro_test_EI = 'N'

    if shapiro_test_ID[1] > 0.05:
        shapiro_test_ID = 'Y'
    else:
        shapiro_test_ID = 'N'

    if shapiro_test_II[1] > 0.05:
        shapiro_test_II = 'Y'
    else:
        shapiro_test_II = 'N'

    if shapiro_test_ED[1] > 0.05:
        shapiro_test_ED = 'Y'
    else:
        shapiro_test_ED = 'N'
    
    print("Shapiro-Wilk Test Results for question [{}]:".format(test_list[i]), shapiro_test_EI, shapiro_test_ID, shapiro_test_II, shapiro_test_ED)

Shapiro-Wilk Test Results for question [1]: Y Y Y Y
Shapiro-Wilk Test Results for question [2]: N N N N
Shapiro-Wilk Test Results for question [3]: Y Y Y Y
Shapiro-Wilk Test Results for question [4]: N N N N
Shapiro-Wilk Test Results for question [5]: Y N Y Y
Shapiro-Wilk Test Results for question [7]: Y N Y Y
Shapiro-Wilk Test Results for question [8]: Y Y Y Y
Shapiro-Wilk Test Results for question [9]: Y Y Y Y
Shapiro-Wilk Test Results for question [10]: Y Y Y Y
Shapiro-Wilk Test Results for question [11]: N Y Y N
Shapiro-Wilk Test Results for question [12]: Y N Y Y
Shapiro-Wilk Test Results for question [13]: N Y Y Y
Shapiro-Wilk Test Results for question [14]: Y N Y Y
Shapiro-Wilk Test Results for question [15]: Y Y Y N
Shapiro-Wilk Test Results for question [16]: N Y Y N
Shapiro-Wilk Test Results for question [17]: Y N N Y
Shapiro-Wilk Test Results for question [18]: N Y Y Y
Shapiro-Wilk Test Results for question [19]: N Y N Y
Shapiro-Wilk Test Results for question [20]: N N N N
Shapiro-Wilk Test Results for question [21]: Y Y Y Y
Shapiro-Wilk Test Results for question [22]: N Y Y Y
Shapiro-Wilk Test Results for question [23]: N N N N
Shapiro-Wilk Test Results for question [24]: N Y Y Y
Shapiro-Wilk Test Results for question [25]: Y Y Y Y
Shapiro-Wilk Test Results for question [26]: N N Y Y
Shapiro-Wilk Test Results for question [27]: N Y Y Y
Shapiro-Wilk Test Results for question [28]: Y Y Y Y
Shapiro-Wilk Test Results for question [29]: N N Y N
Shapiro-Wilk Test Results for question [30]: Y Y Y Y
Shapiro-Wilk Test Results for question [31]: Y Y Y Y
Shapiro-Wilk Test Results for question [32]: N N Y N
Shapiro-Wilk Test Results for question [33]: N Y Y Y
Shapiro-Wilk Test Results for question [34]: Y Y N Y
Shapiro-Wilk Test Results for question [35]: Y N N Y
Shapiro-Wilk Test Results for question [36]: Y N Y Y
Shapiro-Wilk Test Results for question [37]: Y N Y Y
Shapiro-Wilk Test Results for question [38]: N Y N Y
Shapiro-Wilk Test Results for question [39]: N N N N
Shapiro-Wilk Test Results for question [40]: N Y N Y
Shapiro-Wilk Test Results for question [41]: N N N Y
Shapiro-Wilk Test Results for question [42]: Y N N Y
Shapiro-Wilk Test Results for question [43]: N Y N N
Shapiro-Wilk Test Results for question [44]: Y Y Y N
Shapiro-Wilk Test Results for question [45]: N N Y Y
Shapiro-Wilk Test Results for question [46]: N N Y N
Shapiro-Wilk Test Results for question [47]: Y N Y Y
Shapiro-Wilk Test Results for question [48]: N N Y Y
Shapiro-Wilk Test Results for question [49]: Y Y Y Y
Shapiro-Wilk Test Results for question [50]: Y Y Y Y
Shapiro-Wilk Test Results for question [51]: N Y N N
Shapiro-Wilk Test Results for question [52]: Y Y Y Y
Shapiro-Wilk Test Results for question [53]: Y Y Y Y
Shapiro-Wilk Test Results for question [54]: N N Y Y
Shapiro-Wilk Test Results for question [55]: Y N Y Y
Shapiro-Wilk Test Results for question [56]: Y Y Y Y
Shapiro-Wilk Test Results for question [57]: Y Y N N
Shapiro-Wilk Test Results for question [58]: Y Y Y Y
Shapiro-Wilk Test Results for question [59]: N Y Y Y
Shapiro-Wilk Test Results for question [60]: N Y Y Y
Shapiro-Wilk Test Results for question [61]: N N N N
Shapiro-Wilk Test Results for question [62]: N Y Y N
Shapiro-Wilk Test Results for question [63]: N Y Y N

This is my very crude attempt to test the normality of my dataset. If my interpretation of the statistics is correct, if "high normality" is acceptable, then this dataset does pass the normality test. Well, the above is the comment for the original test where I combined every group for normality test and with the wrong interpretation of statistics. Basically, after separating the groups and an hour or trying to normalize data, I have landed the conclusion that a lot of my data cannot be normalized. Thus, I would need to use the Kruskal–Wallis Test for comparison.

In [44]:
EI_dataslip = pd.concat([df.iloc[0:8, 3], df.iloc[32:40, 3]])

In [46]:
EI_dataslip.tolist()

[3, 2, 3, 5, 6, 3, 1, 4, 4, 4, 2, 1, 3, 6, 1, 1]

In [54]:
for i in range(len(test_list)):
    # Perform Levene's Test
    EI_dataclip = pd.concat([df.iloc[0:8, test_list[i]], df.iloc[32:40, test_list[i]]]).tolist()
    ID_dataclip = pd.concat([df.iloc[8:16, test_list[i]], df.iloc[40:48, test_list[i]]]).tolist()
    II_dataclip = pd.concat([df.iloc[16:24, test_list[i]], df.iloc[48:56, test_list[i]]]).tolist()
    ED_dataclip = pd.concat([df.iloc[24:32, test_list[i]], df.iloc[56:64, test_list[i]]]).tolist()
    stat, p_value = stats.levene(EI_dataclip, ID_dataclip, II_dataclip, ED_dataclip)
    print('P-Value for question {}:'.format(test_list[i]), p_value)

P-Value for question 1: 0.9637465001859152
P-Value for question 2: 0.26902327151426175
P-Value for question 3: 0.8763461216283388
P-Value for question 4: 0.5860067913612999
P-Value for question 5: 0.5134516283288368
P-Value for question 7: 0.22230904761224013
P-Value for question 8: 0.7335668451927095
P-Value for question 9: 0.6110202048326384
P-Value for question 10: 0.9106816575122989
P-Value for question 11: 0.8666310484345913
P-Value for question 12: 0.6616195350902486
P-Value for question 13: 0.47062762860084373
P-Value for question 14: 0.5037527297221969
P-Value for question 15: 0.5986247557776283
P-Value for question 16: 0.26167561103114734
P-Value for question 17: 0.7234873719084004
P-Value for question 18: 0.7657137304909334
P-Value for question 19: 0.6162795031381487
P-Value for question 20: 0.7509613852231867
P-Value for question 21: 0.9142379725248921
P-Value for question 22: 0.9223315885745094
P-Value for question 23: 0.30411925164916204
P-Value for question 24: 0.48291980300967596
P-Value for question 25: 0.5181033119691194
P-Value for question 26: 0.9160526837396792
P-Value for question 27: 0.9798394971725055
P-Value for question 28: 0.5890393713540187
P-Value for question 29: 0.5138341111428545
P-Value for question 30: 0.36784727780324966
P-Value for question 31: 0.2562641990031734
P-Value for question 32: 0.7469794505027525
P-Value for question 33: 0.7510564569002558
P-Value for question 34: 0.9593220503958115
P-Value for question 35: 0.47871692966956225
P-Value for question 36: 0.47946831455707384
P-Value for question 37: 0.12744978848578875
P-Value for question 38: 0.9291895428028303
P-Value for question 39: 0.5408126970215523
P-Value for question 40: 0.09609031779048265
P-Value for question 41: 0.858322110011484
P-Value for question 42: 0.9932717716468003
P-Value for question 43: 0.9304843574077154
P-Value for question 44: 0.6951592624275105
P-Value for question 45: 0.4786547516236441
P-Value for question 46: 0.34236008990823286
P-Value for question 47: 0.6207856751805862
P-Value for question 48: 0.5561576428834571
P-Value for question 49: 0.45589637485123624
P-Value for question 50: 0.6694403166289332
P-Value for question 51: 0.4097211106432499
P-Value for question 52: 0.44567283961351134
P-Value for question 53: 0.15748581536068945
P-Value for question 54: 0.2238101441278927
P-Value for question 55: 0.997360504102656
P-Value for question 56: 0.4687256651584889
P-Value for question 57: 0.2467674939351815
P-Value for question 58: 0.08596846614908872
P-Value for question 59: 0.32638362620491257
P-Value for question 60: 0.2083723171015275
P-Value for question 61: 0.6567115165264226
P-Value for question 62: 0.7437334518463006
P-Value for question 63: 0.3037412362605389